[package]
name = "iotdb-mate-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
